DROP TABLE IF EXISTS post;

CREATE TABLE posts(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        title TEXT NULL,
        content TEXT NULL
)